name: Coverage

on:
  push:
    branches: [main]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov
      - uses: extractions/setup-just@v2

      - run: uv sync --dev --no-install-project # special version will be installed by coverage-lcov
      - run: just coverage-python-full
      - run: just coverage-rust
      - uses: codecov/codecov-action@v5
        with:
          files: coverage-rust-from-python.lcov,coverage-python.xml,coverage-rust.lcov
          name: general-run
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: cgevans/equiconc