name: Coverage

on:
  push:
    branches: [main]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v6
      - uses: extractions/setup-just@v2

      - run: uv sync --dev --no-install-project # special version will be installed by coverage-lcov
      - run: just coverage-xml
      - name: Fix absolute paths in coverage.xml
        run: sed -i "s|$PWD/||g" coverage.xml
      - name: Upload coverage to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -f coverage.xml -t ${{ secrets.CODECOV_TOKEN }} -v
